### ISSUE TITLE
npm install firebase fails due to grpc

### ISSUE THREAD

**Issue by dkearsley89** [grpc/grpc-node#121] opened 2017-12-08 04:23 UTC
I'm trying to install firebase to my Angular Project. I have tried with several versions of Node.js but no luck so far.

I get an error similar to that of below:
> grpc@1.7.2 install E:\Development\Angular\RecipeBookProject\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.2/node-v48-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.2 and node@6.12.1 (node-v48 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (E:\Development\Angular\RecipeBookProject\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (E:\Development\Angular\RecipeBookProject\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\Development\Angular\RecipeBookProject\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Development\\Angular\\RecipeBookProject\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=E:\\Development\\Angular\\RecipeBookProject\\node_modules\\grpc\\src\\node\\extension_binary\\node-v48-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=E:\\Development\\Angular\\RecipeBookProject\\node_modules\\grpc\\src\\node\\extension_binary\\node-v48-win32-x64-unknown"
gyp ERR! cwd E:\Development\Angular\RecipeBookProject\node_modules\grpc
gyp ERR! node -v v6.12.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\Development\Angular\RecipeBookProject\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=E:\Development\Angular\RecipeBookProject\node_modules\grpc\src\node\extension_binary\node-v48-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=E:\Development\Angular\RecipeBookProject\node_modules\grpc\src\node\extension_binary\node-v48-win32-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Development\Angular\RecipeBookProject\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Development\\Angular\\RecipeBookProject\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd E:\Development\Angular\RecipeBookProject\node_modules\grpc
node-pre-gyp ERR! node -v v6.12.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\Development\Angular\RecipeBookProject\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=E:\Development\Angular\RecipeBookProject\node_modules\grpc\src\node\extension_binary\node-v48-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=E:\Development\Angular\RecipeBookProject\node_modules\grpc\src\node\extension_binary\node-v48-win32-x64-unknown' (1)
recipe-book-project@0.0.0 E:\Development\Angular\RecipeBookProject
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "firebase"
npm ERR! node v6.12.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.7.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.7.2 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Development\Angular\RecipeBookProject\npm-debug.log
npm ERR! code 1

I can post the contents of npm-debug.log if required.

I'm not sure if this is the correct place to post something like this, but google has come up short and the feedback from npm suggests to do this.

Thanks

**Comment by ygongdev** [comment] 2018-01-16 20:44
I faced a similar problem. For me, the problem seemed to be my antivirus (Kaspersky). Once I disabled it, I was able to install firebase.

**Comment by nsksaisaravana** [comment] 2018-01-28 03:30
@ygongdev Thanks a lot, you saved my day.

**Comment by Levelleor** [comment] 2018-02-01 00:43
This fixed my issue: 

https://stackoverflow.com/questions/48531993/firebase-config-variables-are-not-available-error-with-deploying-functions

**Comment by ksdroid943** [comment] 2018-02-01 13:51
disable antivirus then start same comman. it is working for me.

**Comment by sree332** [comment] 2018-02-03 15:33
disabling anti virus ( kaspersky ) and running the firebase, angularfire2 install worked for me .. just in case if any one is tuck on this issue ..

**Comment by eSamybaxy** [comment] 2018-02-22 15:48
Seems to be an issue with Kaspersky. I paused protection and it installed successfully. You should resume protection right after :).

**Comment by laurenzlong** [comment] 2018-03-07 19:54
The latest firebase-tools (v3.17.5) removes grpc as a dependency, which should resolve these issues. Please upgrade by running `npm i -g firebase-tools`

**Comment by JavaidAhmad** [comment] 2018-03-22 05:22
Issue Resolved!
In my case, I faced the same issue...
I installed 
npm install -g firebase@4.6.2

and removed cap ^ in package.json before firebase version.
#hopeItWillWorkForYou

**Comment by Benyaminrmb** [comment] 2018-04-22 11:55
i got the same error - i have not kaspersky i using (Windows Defender Security Center) and i disable that and run `npm install firebase angularfire2 --save` and not works again ,, how can i fix that ?

**Comment by alchatti** [comment] 2018-05-07 10:32
Same issue, Windows 10 (17134.1), NodeJs (10.0.0), NPM (5.6.0), Yarn (1.6.0) [Stand Alone]
Tried all the above suggestions for both npm & yarn, tried going to NodeJS 8LTS and disabling the antivirus  (Kaspersky) without any success

The only solution worked for me is to install **firebase@4.6.2** or **firebase@4.12.1** , no need for anything else. For me the issue is with 4.13.X

**Comment by nicolasnoble** [comment] 2018-05-17 05:02
Alright, I am going to close this one. The original problem has a known solution, and the rest of this thread is a big confusion of various different issues.

If you experience issues with grpc, please open new issues describing exactly what the problem you are experiencing is. Most of the time your issue is NOT going to be the same as someone else's.

**Closed by nicolasnoble** 2018-05-17 05:02 UTC

**Comment by pritiJI** [comment] 2018-09-21 06:21
@laurenzlong  how to removes grpc as a dependency?
I got the same error to please anyone help me
"The latest firebase-tools (v3.17.5) removes grpc as a dependency, which should resolve these issues. Please upgrade by running npm i -g firebase-tools"

**Comment by Couvel** [comment] 2018-11-05 03:57
Windows Defender also blocks it

**Comment by nicolasnoble** [comment] 2018-11-27 17:47
@sahirvsahirv this has nothing to do with the original report. As I said a couple of comments above, please avoid bumping old, resolved issues, and create new issues fully describing what you're experiencing so we can properly triage what's going on.
