### ISSUE TITLE
gRPC fails to build using gcc 8.

### ISSUE THREAD

**Issue by dmp1ce** [grpc/grpc-node#401] opened 2018-06-16 18:20 UTC
### Problem description
On Arch Linux cannot build grpc-native-core. I followed the instructions here: https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core#build-from-source. Ultimately I would like to to build the Zap wallet which I also have a issue with here: https://github.com/LN-Zap/zap-desktop/issues/420

### Reproduction steps

1. `git clone https://github.com/grpc/grpc-node.git`
2. `cd packages/grpc-native-core/`
3. `git clone https://github.com/grpc/grpc.git`
4. `npm install --build-from-source`
5. Notice these errors: https://bpaste.net/show/659c8d50e916

### Environment
 - Arch Linux (x86-64)
 - Node v10.4.0
 - `pacman -S nodejs`
 - I'm not sure the compiler version
 - building from master branch

**Comment by Empact** [comment] 2018-06-16 22:09
@dmp1ce I would remove the first 2 repro steps because this failure should be independent of `zap-desktop`

**Comment by nicolasnoble** [comment] 2018-06-17 06:01
Nowhere in the instructions are we directing to do this. Also, these reproduction instructions don't make a lot of sense, unless the first line meant to read `git clone https://github.com/grpc/grpc-node.git`.

Ultimately, you're using git wrong. You're cloning `grpc/grpc.git`... somewhere; (1) it's not the proper location and (2) it's not going to be the right tag.

This should work fine instead:

```
git clone --recursive https://github.com/grpc/grpc-node.git
cd grpc-node/packages/grpc-native-core
npm install --build-from-source
```

**Comment by dmp1ce** [comment] 2018-06-17 10:54
Thanks @nicolasnoble. I had a bad copy and paste in my instructions. My steps to reproduce should be correct now.

I did follow your steps and got the following error messages: https://bpaste.net/show/b1d75e081640

**Comment by nicolasnoble** [comment] 2018-06-17 16:14
That's more interesting, and that's a core issue. I really need to know your compiler however in order to send them a full report. 

Try `cc --version`.

Additionally, there shouldn't be any reason for you to build grpc. After reading the other issue you've linked, I believe you are using the installation instructions incorrectly. 

Also cc @ejona86 who I know is an Arch Linux fan.

**Comment by dmp1ce** [comment] 2018-06-17 16:58
```
> cc --version
cc (GCC) 8.1.1 20180531
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I'll check https://github.com/LN-Zap/zap-desktop/issues/420 for building Zap incorrectly.

**Comment by nicolasnoble** [comment] 2018-06-17 18:18
Ugh, we have a few more compilation issues with gcc 8 then. Great. Thanks.

**Comment by nicolasnoble** [comment] 2018-06-17 20:54
Should eventually be fixed by grpc/grpc#15532

**Comment by ejona86** [comment] 2018-06-18 15:59
It looks like you've got this covered. @nicolasnoble, if you need anything from me just mention me again.

**Comment by mastersingh24** [comment] 2019-03-19 17:41
@nicolasnoble  - so how did you guys build the Alpine / musl precompiled binary using the Node 10 image?  I guess at the time perhaps the Node 10 image was based on Alpine 3.8 (which uses gcc 6.4.0) versus gcc 8.2 on Alpine 3.9?

**Comment by nicolasnoble** [comment] 2019-03-19 18:13
This is exactly the source of issues I mentioned in #762 we're now trying to fix since this was never really done otherwise. :-P

**Comment by murgatroid99** [comment] 2021-05-11 21:26
The `grpc` package is now deprecated. We recommend instead using `@grpc/grpc-js`, which doesn't have these kinds of issues.

**Closed by murgatroid99** 2021-05-11 21:26 UTC
Labels: bug, customer issue, package: grpc
