### ISSUE TITLE
When updating to 1.12.0 from 1.11.3 I get ENOENT error

### ISSUE THREAD

**Issue by aaltat** [grpc/grpc-node#2287] opened 2022-12-02 18:14 UTC
### Problem description
When running command `npm run grpc_tools_node_protoc` I get ENOENT error. 

### Reproduction steps
`npm run grpc_tools_node_protoc -- --js_out=import_style=commonjs,binary:/Users/user/workspace/robotframework-playwright/node/playwright-wrapper/generated --grpc_out=grpc_js:/Users/user/workspace/robotframework-playwright/node/playwright-wrapper/generated --plugin=protoc-gen-grpc=/Users/user/workspace/robotframework-playwright/node_modules/.bin/grpc_tools_node_protoc_plugin -I ./protobuf protobuf/*.proto`

```
> robotframework-playwright@14.2.1 grpc_tools_node_protoc
> grpc_tools_node_protoc --js_out=import_style=commonjs,binary:/Users/user/workspace/robotframework-playwright/node/playwright-wrapper/generated --grpc_out=grpc_js:/Users/user/workspace/robotframework-playwright/node/playwright-wrapper/generated --plugin=protoc-gen-grpc=/Users/user/workspace/robotframework-playwright/node_modules/.bin/grpc_tools_node_protoc_plugin -I ./protobuf protobuf/playwright.proto

/Users/userworkspace/robotframework-playwright/node_modules/grpc-tools/bin/protoc.js:41
    throw error;
    ^

Error: spawn /Users/user/workspace/robotframework-playwright/node_modules/grpc-tools/bin/protoc ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /Users/user/workspace/robotframework-playwright/node_modules/grpc-tools/bin/protoc',
  path: '/Users/user/workspace/robotframework-playwright/node_modules/grpc-tools/bin/protoc',
  spawnargs: [
    '--plugin=protoc-gen-grpc=/Users/user/workspace/robotframework-playwright/node_modules/grpc-tools/bin/grpc_node_plugin',
    '--js_out=import_style=commonjs,binary:/Users/user/workspace/robotframework-playwright/node/playwright-wrapper/generated',
    '--grpc_out=grpc_js:/Users/user/workspace/robotframework-playwright/node/playwright-wrapper/generated',
    '--plugin=protoc-gen-grpc=/Users/user/workspace/robotframework-playwright/node_modules/.bin/grpc_tools_node_protoc_plugin',
    '-I',
    './protobuf',
    'protobuf/playwright.proto'
  ],
  cmd: '/Users/user/workspace/robotframework-playwright/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/Users/user/workspace/robotframework-playwright/node_modules/grpc-tools/bin/grpc_node_plugin --js_out=import_style=commonjs,binary:/Users/user/workspace/robotframework-playwright/node/playwright-wrapper/generated --grpc_out=grpc_js:/Users/user/workspace/robotframework-playwright/node/playwright-wrapper/generated --plugin=protoc-gen-grpc=/Users/user/workspace/robotframework-playwright/node_modules/.bin/grpc_tools_node_protoc_plugin -I ./protobuf protobuf/playwright.proto'
```

### Environment
 - macOS Venture 13.0.1
 - node: v16.15.1 npm: 9.1.3
 - Brew
 - grpc-tools 1.12.0

### Additional context
This error only happen with Mac, our CI runs also Linux and Windows, this error is not visible: https://github.com/MarketSquare/robotframework-browser/pull/2449

**Comment by robertfreund** [comment] 2022-12-02 20:23
I can confirm this as well on Mac arm64. The grpc-tools seem to be installed in grpc-tools/bin/GNUSpareFiles.0/

**Comment by murgatroid99** [comment] 2022-12-02 20:49
I see that. I don't know what happened there. There have been no changes since the last release that would clearly affect the Mac build.

**Comment by murgatroid99** [comment] 2022-12-05 17:22
I published a fix for this in version 1.12.1. Please try it out.

**Closed** 2022-12-05 17:21 UTC

**Comment by aaltat** [comment] 2022-12-05 18:16
Well, better, but there is now different error 
```
> robotframework-playwright@14.3.0 grpc_tools_node_protoc
> grpc_tools_node_protoc --js_out=import_style=commonjs,binary:/Users/runner/work/robotframework-browser/robotframework-browser/node/playwright-wrapper/generated --grpc_out=grpc_js:/Users/runner/work/robotframework-browser/robotframework-browser/node/playwright-wrapper/generated --plugin=protoc-gen-grpc=/Users/runner/work/robotframework-browser/robotframework-browser/node_modules/.bin/grpc_tools_node_protoc_plugin -I ./protobuf protobuf/playwright.proto

dyld: Symbol not found: __ZTTNSt3__[11](https://github.com/MarketSquare/robotframework-browser/actions/runs/3622594524/jobs/6107495797#step:7:12)4basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc (which was built for Mac OS X [12](https://github.com/MarketSquare/robotframework-browser/actions/runs/3622594524/jobs/6107495797#step:7:13).0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc
/Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc.js:41
    throw error;
    ^
```

Full error in https://github.com/MarketSquare/robotframework-browser/actions/runs/3622594524/jobs/6107495797

Again works with Windows and Linux, but not with Mac.

**Comment by aaltat** [comment] 2022-12-05 18:16
Well, better, but there is now different error 
```
> robotframework-playwright@14.3.0 grpc_tools_node_protoc
> grpc_tools_node_protoc --js_out=import_style=commonjs,binary:/Users/runner/work/robotframework-browser/robotframework-browser/node/playwright-wrapper/generated --grpc_out=grpc_js:/Users/runner/work/robotframework-browser/robotframework-browser/node/playwright-wrapper/generated --plugin=protoc-gen-grpc=/Users/runner/work/robotframework-browser/robotframework-browser/node_modules/.bin/grpc_tools_node_protoc_plugin -I ./protobuf protobuf/playwright.proto

dyld: Symbol not found: __ZTTNSt3__[11](https://github.com/MarketSquare/robotframework-browser/actions/runs/3622594524/jobs/6107495797#step:7:12)4basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc (which was built for Mac OS X [12](https://github.com/MarketSquare/robotframework-browser/actions/runs/3622594524/jobs/6107495797#step:7:13).0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc
/Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc.js:41
    throw error;
    ^
```

Full error in https://github.com/MarketSquare/robotframework-browser/actions/runs/3622594524/jobs/6107495797

Again works with Windows and Linux, but not with Mac.

**Comment by murgatroid99** [comment] 2022-12-05 18:20
That's a different bug. Can you file a separate issue with the information about it?

**Comment by aaltat** [comment] 2022-12-05 18:25
No problem,  please see https://github.com/grpc/grpc-node/issues/2289
