### ISSUE TITLE
`@grpc/proto-loader` discards messages

### ISSUE THREAD

**Issue by dvisztempacct** [grpc/grpc-node#439] opened 2018-07-18 01:30 UTC
It looks like `load` and `loadSync` both call `getAllServices` discarding the rest before returning you a package definition.

This leaves me without useful functions like `MyMessage.encode` which i might want for reasons beyond just using `node-grpc` the way most people probably do.

**Comment by nicolasnoble** [comment] 2018-07-18 04:19
That's on purpose, really, in order to abstract protobufjs away from the end user, since its API can change from one minor version to another. If you need the message types directly, please use protobufjs directly.

Note that you can theoretically write your own loader in this case, and replace `@grpc/proto-loader` completely with your own custom code. I actually wrote such code for a personal project of mine, because just like you, I needed to have access to protobufjs' objects, and you can see this code here: https://github.com/grumpycoders/papan/blob/master/src/server/common/proto.js - the return value of my loader contains an additional `rootProto` field that exposes the protobufjs' root object, and I'm calling `grpc.loadObject` directly instead of using the helper load functions.

I'll close this one as this is really not a bug.

**Closed by nicolasnoble** 2018-07-18 04:19 UTC

**Comment by dvisztempacct** [comment] 2018-07-18 13:44
Thanks for such a fast reply :)

This is the direction I was headed in, but I was hoping there was a solution that would require less knowledge!

Your code looks much simpler than `@grpc/proto-loader`. This in particular:

```javascript
  const proto = await protobufjs.load(filenames, root)
  const ret = grpc.loadObject(proto, { protobufjsVersion: 6 })
```

Do you happen to know if there's a synchronous replacement for `protobufjs.load`? I've tried `loadSync` but I get `TypeError: root.loadSync is not a function`

**Comment by dvisztempacct** [comment] 2018-07-18 15:00
I tried out your code, and I am noticing that the objects representing my message types are just empty objects. Maybe they have some hidden features that I can't see, but their prototype and constructor are both consistent with a POJO à la `{}`.

**Comment by nicolasnoble** [comment] 2018-07-18 15:51
I don't really know what to say about this.

The trick is to make sure that you know how to use protobufjs, which is a separate product from grpc. 

And the only reason to use loadObject is to avoid parsing the proto files twice, but if you don't care about this last part, you can always use proto-loader in parallel to protobufjs and effectively parse the files twice.
