### ISSUE TITLE
Prebuilt gRPC doesn't work with the Ubuntu 18.04 nodejs runtime.

### ISSUE THREAD

**Issue by przemek-instapage** [grpc/grpc-node#341] opened 2018-05-16 14:13 UTC
While trying to use Google PubSub Node.js library that uses grpc-node lib I get an error:
`node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node: undefined symbol: SSL_library_init`

I have tried to reinstall this module but that does not help.

**Comment by nicolasnoble** [comment] 2018-05-16 14:55
Please give us more details on this. What's your version of nodejs, operating system, environnement, and any other detail that might be helpful.

**Comment by przemek-instapage** [comment] 2018-05-16 15:26
Here you are:

```
$ node -v
v8.10.0

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

$ npm -v
3.5.2

$ apt list --installed | grep ssl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libgnutls-openssl27/bionic,now 3.5.18-1ubuntu1 amd64 [installed]
libio-socket-ssl-perl/bionic,bionic,now 2.056-1 all [installed]
libnet-smtp-ssl-perl/bionic,bionic,now 1.04-1 all [installed]
libnet-ssleay-perl/bionic,now 1.84-1build1 amd64 [installed]
libssl-dev/bionic,now 1.1.0g-2ubuntu4 amd64 [installed]
libssl-doc/bionic,bionic,now 1.1.0g-2ubuntu4 all [installed]
libssl1.0.0/bionic,now 1.0.2n-1ubuntu5 amd64 [installed]
libssl1.1/bionic,now 1.1.0g-2ubuntu4 amd64 [installed,automatic]
openssl/bionic,now 1.1.0g-2ubuntu4 amd64 [installed]
perl-openssl-defaults/bionic,now 3build1 amd64 [installed,automatic]
python-openssl/bionic,bionic,now 17.5.0-1ubuntu1 all [installed,automatic]
ssl-cert/bionic,bionic,now 1.0.39 all [installed]

```
Do you need anything more?

**Comment by nicolasnoble** [comment] 2018-05-16 15:30
Is your version of node installed via nvm or apt ?

**Comment by przemek-instapage** [comment] 2018-05-16 15:33
Via __apt__ ```nodejs/bionic,now 8.10.0~dfsg-2 amd64 [installed]```

**Comment by nicolasnoble** [comment] 2018-05-16 15:36
Great, thanks. I can then make a bug report to Ubuntu, because I can confirm their nodejs package is broken. That's the rootcause issue here.

**Comment by nicolasnoble** [comment] 2018-05-16 15:43
In the meantime, you can make this work for your machine by doing an `npm rebuild --build-from-source`. I just confirmed this works.

**Comment by nicolasnoble** [comment] 2018-05-16 15:43
For reference, the Ubuntu package is breaking the node-gyp spec explained here: https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL

**Comment by przemek-instapage** [comment] 2018-05-16 15:46
@nicolasnoble I have got the same error message, even after using `npm rebuild --build-from-source` command.

**Comment by nicolasnoble** [comment] 2018-05-16 15:52
Hmmm, that's odd. I guess I am missing something. Could you try reproducing everything inside of docker? I may have been too quick on my conclusion.

```
$ docker run -t -i ubuntu:18.04 bash -l
# apt update
# apt install nodejs npm
# npm install ...
```

**Comment by nicolasnoble** [comment] 2018-05-16 15:55
Or more specifically, if you could give us a reproduction case that exhibits the issue within a ubuntu:18.04 docker image, that'd be great.

**Comment by nicolasnoble** [comment] 2018-05-16 16:26
So that's disturbing. The nodejs runtime is supposed to expose its SSL symbols to any extension. For some reasons, on your environment only, this doesn't seem to work fine. There might be interference caused by another package or daemon that would impose this. My gut feeling would be apparmor, but it's a long shot.

Could you check the contents of your syslog or dmesg buffer as you try to load the extension to see if something somewhere is denying the load?

Given it's on your environment only, I would be tempted to close this one as unreproducible, but I'd still love to get to the bottom of this.

How did you install your environment? Is it desktop? Did you upgrade from a former version of ubuntu? Did you install any custom package? Maybe give me the full output of `dpkg -l`, and we can try reproducing your issue in a virtualbox desktop, if you did install a desktop version.

**Comment by przemek-instapage** [comment] 2018-05-16 17:12
There is nothing in syslog/dmesg that seems related to this issue. This is the desktop installation, the OS was upgraded from Ubuntu 16.04. I have attached the full output of `dpkg -l` 

Thanks for your help, I understand that's a problem with my environment only, so I don't mind if you close this issue. Anyway I will try to solve it on my own in my free time. 
[dpkg_list.txt](https://github.com/grpc/grpc-node/files/2010041/dpkg_list.txt)

**Comment by przemek-instapage** [comment] 2018-05-17 08:18
Just FYI, to work around my problem, I have installed _node v10.1.0_ through _nodesource_ repository and that way everything works just fine.

**Comment by gregd72002** [comment] 2018-05-30 15:04
Same problem here. Stock Ubuntu 18.04, nodejs: 8.10.0, npm: 3.5.2. I will try using nodesource instead

**Comment by gregd72002** [comment] 2018-05-30 16:10
It was a fresh install. Not sure if this helps but it was a brand new Azure VM: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/Canonical.UbuntuServer1804LTS?tab=Overview

**Comment by nicolasnoble** [comment] 2018-05-30 16:42
It helps a lot, yes, thanks.

**Comment by nicolasnoble** [comment] 2018-05-31 19:17
@gregd72002 alright, I'd love a bit more explicit reproduction case, because I'm at a loss. I've created an Azure VM following the link you gave, clicked all the `next` button selecting all the defaults. Eventually, I ended up on an Ubuntu VM in which I did `npm install nodejs npm` to install node.

Afterward, I did `npm install @google-cloud/pubsub` which transitively picked grpc@1.12.2. Then, I managed to safely do `require('grpc')` and `require('@google-cloud/pubsub')`, meaning I can't reproduce it on Azure either.

**Comment by fit-aditya** [comment] 2018-06-19 06:07
I can confirm that installing nodejs v10.4.1 from nodesource and running `npm rebuild --build-from-source` solves this problem.
I am on Ubuntu 18.04 upgraded from 16.04

**Comment by nicolasnoble** [comment] 2018-06-19 06:33
I can't stress this enough: we are 100% unable to reproduce this, no matter how we tried. If anyone can provide reproducible steps that creates an environment where this happens, I would be really glad.

**Comment by hi5san** [comment] 2018-06-29 03:35
@nicolasnoble I have a ubuntu 18.04 LTS vagrant box provisioned configuration that reproduces the issue (the npm rebuild does not help), but unsure if it would help as its not configured to be a clean/simple testcase.  Will you be interested in it?

**Comment by nicolasnoble** [comment] 2018-06-29 05:42
If you're willing to either image it and give the image to me, or give me access to it, yes.

**Comment by hi5san** [comment] 2018-06-29 16:38
@nicolasnoble I appreciate your accepting the offer despite it might not be what you're looking for.  Thank you.  I've prepared both Vagrantfile and a box image.  Could I send the information to your email address or other direct method?

**Comment by nicolasnoble** [comment] 2018-06-29 19:48
I just sent you an e-mail from my work address.

**Comment by nicolasnoble** [comment] 2018-06-30 00:04
It reproduces alright, and this is gnarly.

**Comment by nicolasnoble** [comment] 2018-06-30 00:31
Okay, I know exactly what's going on now, thanks a lot for the image and the repro case, @hi5san. Unfortunately, this isn't fixable, at all. I managed to find at least one another npm package (uws) that is plagued with the same exact problem, so this isn't on gRPC. 

I am going to try creating a small reproduction case to submit a bug in Ubuntu and/or Debian - because that's an actual issue with the package itself.

The node binary in Ubuntu's package is just not conforming to the node extension ABI, and as such, will never be able to load any precompiled package out there that uses SSL. But this non-conformance is due to Debian's rules around OpenSSL, therefore I have little hopes this will ever get fixed, since fixing it would make the package non-conformant.

Your best bet in using gRPC at the moment under Ubuntu 18.04 is to:

 - install nodejs using nvm
or
 - install gRPC by compiling from source: `npm install --build-from-source=grpc`.

I will leave the issue opened for the time being, as this is clearly a problem, and we know its cause, but don't expect any traction from it from our end beside the provided workarounds above.

**Comment by nicolasnoble** [comment] 2018-06-30 00:34
Also the reason it took me so long to reproduce is because we're lazily loading OpenSSL's symbols. We don't get into trouble until creating an actual secure connection.

**Comment by Mambix** [comment] 2018-07-02 08:58
fyi

Building gRPC from source did not work for me. I did
```
npm unistall grpc
npm install --build-from-source=grpc
```

So I wen the nvm way:
```
sudo apt purge nodejs*
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
nvm install node
```

After this I removed node_modules folder and ran `npm i` just in case.
And now it's working 👍

**Comment by hi5san** [comment] 2018-07-02 15:23
@nicolasnoble Thanks for your expertise and prompt action.

fyi - 
@Mambix Thanks for your tip.  It was same for me.  Here's the nodesource way that I used to workaround it fyi 👍 .
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
apt-get install -y nodejs
```

**Comment by nicolasnoble** [comment] 2018-07-03 13:07
Filed a detailed Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/1779863 - please follow along there instead.

**Comment by relic-** [comment] 2018-07-19 15:38
I am experiencing same issue on Arch Linux, but rebuilding from source on node v8.10.x and v10.x does not help, as since node v8.10 arch packages use openssl 1.1.

So far the only thing that worked for me was downgrading to v8.9.0 (last node carbon using openssl 1.0) or building node from source and linking to openssl-1.0. 

It is not a bug on arch per se, as it's supposed to be rolling release. 

Maybe, until grpc supports openssl 1.1, grpc-node could check openssl version and show more helpful error message?

**Comment by murgatroid99** [comment] 2018-07-19 15:56
Have you tried using the official Node.js Linux binary distribution that is distributed on the Node website?

**Comment by relic-** [comment] 2018-07-19 16:04
I forgot about those. Tested 8.11.3, it works.

**Comment by nicolasnoble** [comment] 2018-07-19 17:38
Also, it's not an issue of gRPC supporting OpenSSL 1.1 or not. It's an issue that there are ABI breakages between OpenSSL 1.0 and 1.1, and that the official nodejs 8 distribution is built against OpenSSL 1.0, so our prebuilt binaries are picking up OpenSSL 1.0's ABI. Loading a binary module that expects OpenSSL 1.0's ABI into a runtime that exposes OpenSSL 1.1's ABI will never work.

**Comment by nicolasnoble** [comment] 2018-07-19 17:39
In other words, if you are building NodeJS 8 against OpenSSL 1.1, you are breaking NodeJS' ABI, and your runtime will never be able to load prebuilt binary extensions that use OpenSSL.

**Comment by nicolasnoble** [comment] 2018-07-19 17:40
So, if arch linux does the same as Ubuntu, then it's also an arch linux bug, as this breaks the official NodeJS ABI.

**Comment by nicolasnoble** [comment] 2018-07-19 18:08
Added an arch linux bug: https://bugs.archlinux.org/task/59394

**Comment by xgdgsc** [comment] 2018-07-22 00:29
Hi. I' m using the nodejs 8 deb package from official site (not the ubuntu repo version) . When I do npm rebuild for grpc with one of my electron project, I get following compiling errors:
```
CXX(target) Release/obj.target/grpc_node/ext/call.o
In file included from ../ext/call.cc:26:0:
../ext/call.h:106:8: error: ‘AsyncResource’ in namespace ‘Nan’ does not name a type
   Nan::AsyncResource *async_resource;
        ^~~~~~~~~~~~~
In file included from ../ext/call.cc:27:0:
../ext/call_credentials.h:82:8: error: ‘AsyncResource’ in namespace ‘Nan’ does not name a type
   Nan::AsyncResource *async_resource;
        ^~~~~~~~~~~~~
../ext/call_credentials.h: In constructor ‘grpc::node::plugin_callback_data::plugin_callback_data(const char*, grpc_credentials_plugin_metadata_cb, void*)’:
../ext/call_credentials.h:71:9: error: class ‘grpc::node::plugin_callback_data’ does not have any field named ‘async_resource’
         async_resource(NULL) {
         ^~~~~~~~~~~~~~
../ext/call_credentials.h:73:5: error: ‘async_resource’ was not declared in this scope
     async_resource = new Nan::AsyncResource("grpc:plugin_callback_data");
     ^~~~~~~~~~~~~~
../ext/call_credentials.h:73:26: error: expected type-specifier
     async_resource = new Nan::AsyncResource("grpc:plugin_callback_data");
                          ^~~
../ext/call_credentials.h: In destructor ‘grpc::node::plugin_callback_data::~plugin_callback_data()’:
../ext/call_credentials.h:76:12: error: ‘async_resource’ was not declared in this scope
     delete async_resource;
            ^~~~~~~~~~~~~~
../ext/call.cc: In constructor ‘grpc::node::tag::tag(Nan::Callback*, grpc::node::OpVec*, grpc::node::Call*, v8::Local<v8::Value>)’:
../ext/call.cc:450:7: error: class ‘grpc::node::tag’ does not have any field named ‘async_resource’
       async_resource(NULL),
       ^~~~~~~~~~~~~~
../ext/call.cc:454:3: error: ‘async_resource’ was not declared in this scope
   async_resource = new Nan::AsyncResource("grpc:tag");  // Needs handle scope.
   ^~~~~~~~~~~~~~
../ext/call.cc:454:24: error: expected type-specifier
   async_resource = new Nan::AsyncResource("grpc:tag");  // Needs handle scope.
                        ^~~
../ext/call.cc: In destructor ‘grpc::node::tag::~tag()’:
../ext/call.cc:460:10: error: ‘async_resource’ was not declared in this scope
   delete async_resource;
          ^~~~~~~~~~~~~~
../ext/call.cc: In function ‘void grpc::node::CompleteTag(void*, const char*)’:
../ext/call.cc:476:41: error: ‘struct grpc::node::tag’ has no member named ‘async_resource’
     callback->Call(2, argv, tag_struct->async_resource);
                                         ^~~~~~~~~~~~~~
../ext/call.cc:479:41: error: ‘struct grpc::node::tag’ has no member named ‘async_resource’
     callback->Call(1, argv, tag_struct->async_resource);
                                         ^~~~~~~~~~~~~~

```

**Comment by nicolasnoble** [comment] 2018-07-22 00:32
@xgdgsc: this is a different problem altogether from this one. This one is about prebuilt binaries, and yours is about compiling. Please don't mix things up to avoid confusion, and open a new issue, following our issue template filing all the details so we can help you properly.

I will delete both your comment and mine in a little while.

**Comment by kwek20** [comment] 2018-08-14 14:35
@hi5san and @Mambix together solved it for me! Thanks guys.
Also thanks @nicolasnoble  for trying to fix it!

**Comment by nicolasnoble** [comment] 2018-08-14 19:29
Note that Ubuntu and arch have agreed to fix this.

**Comment by ahmadalibaloch** [comment] 2018-09-11 23:08
used `nvm` to install `node 10.10`, set it on work and then run `npm rebuild` in the directory and then it worked.

**Comment by nicolasnoble** [comment] 2018-09-26 18:13
So, the nodejs Ubuntu package has been fixed and published as of a few hours ago, and therefore I can close this issue. This was an interesting journey.

**Closed by nicolasnoble** 2018-09-26 18:13 UTC
