### ISSUE TITLE
Http2 connect errors never disclosed in trace/error log output; enableTrace not supported

### ISSUE THREAD

**Issue by gold-plated-hammer** [grpc/grpc-node#2468] opened 2023-06-20 10:40 UTC
As noted in a remark in [issue 1974](https://github.com/grpc/grpc-node/issues/1974),

> [When] cannot connect to server ...  no error message from [grpc-js]

This is due to the [unimplemented trace output in transport.ts](https://github.com/grpc/grpc-node/blob/25e2845d6cc162275e815d9983ee87636ed8e54a/packages/grpc-js/src/transport.ts#L487). This completely obscures the underlying cause of connection errors, preventing direct diagnosis.

In addition, when diagnosing TLS connection issues a powerful technique is to set the [enableTrace ](https://nodejs.org/docs/latest-v18.x/api/tls.html#tlsconnectoptions-callback)option in [http2.connect()](https://nodejs.org/docs/latest-v18.x/api/http2.html#http2connectauthority-options-listener), but this is not supported.

### Reproduction steps
Create a working gRPC client with TLS enabled.
Replace the server certificate with one that is signed by a CA not in the client's truststore.
Result => uninformative error 14 UNAVAILABLE at the client and no other information in the gRPC log, even with GRPC_TRACE=all.

### Environment
 - Linux Ubuntu 20.04 amd64
 - Node 18
 - @grpc/grpc-js 1.8.15

**Comment by murgatroid99** [comment] 2023-06-20 23:28
> This is due to the [unimplemented trace output in transport.ts](https://github.com/grpc/grpc-node/blob/25e2845d6cc162275e815d9983ee87636ed8e54a/packages/grpc-js/src/transport.ts#L487).

Oops. This is fixed in version 1.8.16.

Adding the ability to enable TLS tracing seems reasonable too. It should be possible to do that with a new channel option.

**Comment by gold-plated-hammer** [comment] 2023-06-21 01:44
It may make sense for the connection error event to be logged at ERROR level. But any disclosure will be a welcome improvement. Thanks.

**Comment by murgatroid99** [comment] 2023-08-02 23:51
As of the 1.9.0 release, the channel option `grpc-node.tls_enable_trace` can now be used to enable TLS tracing for connections created by a client/channel or server object.

**Comment by murgatroid99** [comment] 2023-12-01 15:57
As of 1.9.6, call errors caused by failing to establish a connection to a server now include the text of the latest connection error.

**Closed by murgatroid99** 2023-12-01 15:57 UTC
Labels: feature request, package: @grpc/grpc-js
