### ISSUE TITLE
Fails to install on node v11

### ISSUE THREAD

**Issue by mantielero** [grpc/grpc-node#614] opened 2018-11-09 16:03 UTC
### Problem description
It fails to install on ArchLinux with node v11.

### Reproduction steps
In an updated ArchLinux system with node v11. I just did:

```bash
npm i --save grpc
```

### Environment
 - OS name, version and architecture: ArchLinux amd64,  Linux 4.18.16-arch1-1-ARCH, Linux mountain 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
 - Node version 11.1.0
 - Node installation method npm
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version gRPC@1.16.0

### Additional context
I was trying to install firebase, but it fails when trying install grpc. I am a newbie trying to learn a bit of javascript. 

[2018-11-09T15_59_07_748Z-debug.log](https://github.com/grpc/grpc-node/files/2566556/2018-11-09T15_59_07_748Z-debug.log)

**Comment by nicolasnoble** [comment] 2018-11-09 16:16
Duplicate of #594. Please downgrade to node 10 for now.

**Closed by nicolasnoble** 2018-11-09 16:16 UTC
