### ISSUE TITLE
grpc v1.13.1 compile failed

### ISSUE THREAD

**Issue by poppinlp** [grpc/grpc-node#463] opened 2018-07-27 03:19 UTC
### Problem description

I try to install grpc 1.13.1 today. But it compile failed. Here's the error log:

```
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node" "/Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node /Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node" "/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc
node-pre-gyp ERR! node -v v10.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node /Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.oexec install script
../deps/grpc/src/core/lib/backoff/backoff.cc:19:10: fatal error: 'grpc/support/port_platform.h' file not found
#include <grpc/support/port_platform.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.░⸩ ⠹ install: info lifecycle grpc@1.13.1~install: Failed to exec install script
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node" "/Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.13.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/poppinl/.npm/_logs/2018-07-27T02_59_16_951Z-debug.log
```

But v1.13.0 works well.

### Reproduction steps

I just install grpc 1.13.1.

### Environment

- macOS 10.13.6 x64
- 10.7.0
- nvm
- gRPC@1.13.1

**Comment by nicolasnoble** [comment] 2018-07-27 16:50
I just tried to do `npm install grpc --build-from-source` on MacOS 10.13.6 x64 with node 10.7.0 and npm 6.1.0, and it worked fine for me. Could you provide the full, unabridged log, including the file /Users/poppinl/.npm/_logs/2018-07-27T02_59_16_951Z-debug.log?

**Comment by poppinlp** [comment] 2018-07-30 06:36
Hi. I've try it again and it's still there. Here's what i got.

The output from `npm i`:

```
$ rm -rf node_modules && npm i

> fsevents@1.2.4 install /Users/poppinl/Documents/code/ricequant/pudge/node_modules/fsevents
> node install

[fsevents] Success: "/Users/poppinl/Documents/code/ricequant/pudge/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> grpc@1.13.1 install /Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://npm.taobao.org/mirrors/grpc/grpc-precompiled-binaries/node/grpc/v1.13.1/node-v64-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.13.1 and node@10.7.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.13.1 and node@10.7.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node" "/Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node /Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node" "/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc
node-pre-gyp ERR! node -v v10.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node /Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.oexec install script
../deps/grpc/src/core/lib/backoff/backoff.cc:19:10: fatal error: 'grpc/support/port_platform.h' file not found
#include <grpc/support/port_platform.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.░⸩ ⠧ install: info lifecycle grpc@1.13.1~install: Failed to exec install script
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/poppinl/.nvm/versions/node/v10.7.0/bin/node" "/Users/poppinl/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/poppinl/Documents/code/ricequant/pudge/node_modules/grpc
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.13.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/poppinl/.npm/_logs/2018-07-30T06_29_50_769Z-debug.log
```

Here's the debug log file `/Users/poppinl/.npm/_logs/2018-07-30T06_29_50_769Z-debug.log` which mentioned above:

[2018-07-30T06_29_50_769Z-debug.log](https://github.com/grpc/grpc-node/files/2239912/2018-07-30T06_29_50_769Z-debug.log)

I hope this help.

**Comment by poppinlp** [comment] 2018-07-30 06:41
And according to your new mirror for bin file which is mentioned [here](https://github.com/grpc/grpc-node/issues/238#issuecomment-408462010). I can install 1.13.1 right now. :)

**Comment by nicolasnoble** [comment] 2018-07-30 10:39
Yeah, I don't really know what's going on in here... Logs aren't really helpful, and I really can't reproduce it.

As you're likely to not have the issue again due to the new hosting, I'm going to close this one since we can't reproduce it.

**Closed by nicolasnoble** 2018-07-30 10:39 UTC
Labels: requires reporter action
