### ISSUE TITLE
Error: Cannot find module 'protobufjs'

### ISSUE THREAD

**Issue by Urkass** [grpc/grpc-node#1011] opened 2019-08-23 16:54 UTC
### Problem description
Can't resolve path to `protobufjs` d.ts file

### Reproduction steps
Just `tsc` file that imports `grpc`
Repo to reproduce: https://github.com/Urkass/exampleForGrpc (`npm i && npm start`)

### Environment
- macOS Mojave
- Node version v11.15.0
- Node installation method : nvm
- Package name and version: gRPC@^1.23.2

### Additional context
Error:
```
node_modules/grpc/index.d.ts:21:55 - error TS2307: Cannot find module 'protobufjs'.

21   import { Message, Service as ProtobufService } from "protobufjs";
```

`grpc` dependency `protobufjs@5.0.3` doesn't have any typings. d.ts file is included in older versions of protobufjs.  
I guess you can't reproduce it in your repo because there are several `protobufjs` packages. Newer one is installed in root node_modules. Older one is installed in `grpc-native-core/node_modules`.

**Comment by murgatroid99** [comment] 2019-08-23 17:04
This is a duplicate of #572. As mentioned there, a possible fix is coming soon.

**Closed by murgatroid99** 2019-08-23 17:04 UTC
