### ISSUE TITLE
Deadline examples/docs could use clarification

### ISSUE THREAD

**Issue by jhump** [grpc/grpc-node#2763] opened 2024-05-30 17:48 UTC
The examples folder indicates that a deadline is configured via adding a `deadline` property to the *second* argument when invoking an RPC. In the examples, the value is a `Date` value that represents the deadline ([link](https://github.com/grpc/grpc-node/blob/master/examples/deadline/client.js#L37-L39)):

```jsx
const deadline = new Date();
    deadline.setSeconds(deadline.getSeconds() + 1);
    client.unaryEcho({message: message}, {deadline}, (error, value) => {
        // ...
    });
```

However, in practice, this does not work. This results in settings a request header named `Deadline` whose value is a large integer (milliseconds since epoch of that date).

It turns out that the code needs to set that in the *third* argument, which is a `CallOptions` object. (The second argument is metadata.)

Quite confusingly, the tests (in [packages/grpc-js/test/test-call-propagation.ts](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/test/test-call-propagation.ts)) look like they provide the deadline in the second argument, not the third. I’m not sure how they are passing. Does the handler do some sort of inspection of the arguments to dynamically decide how to interpret the positional args?

In any event, this should be better documented, and the examples should be updated.

**Comment by murgatroid99** [comment] 2024-05-30 17:58
How are you getting this result? When I run the examples I don't see that behavior, I see the intended behavior of setting the deadline and having requests end with the DEADLINE_EXCEEDED status.

**Comment by jhump** [comment] 2024-05-30 18:04
@murgatroid99, I'll have to dig through the commit history to find the commit where it was failing. The working code looks like so:
```js
const call = client.unary(
      uReq,
      metadata,
      callOptions,
      (err: ServiceError | null, response: UnaryResponse) => {
          // ...
      }
    );
```

Previously, based on the docs indicating a `deadline` in the second parameter, I think the second paramter was previously a combined object with both request metadata and a deadline key. It's unclear from the docs that _wouldn't_ work. And when there was no other request metadata, it would have basically looked like exactly like the example.

@smaye81, can you help me unearth a better snippet that repros this?

**Comment by murgatroid99** [comment] 2024-05-30 18:09
Just to clarify, the handler *does* inspect the arguments to dynamically decide how to interpret the positional arguments. It is unambiguous because `metadata` must be an instance of the `Metadata` class, `callOptions` must be an object, and the `callback` argument must be a function.

**Comment by jhump** [comment] 2024-05-30 18:19
Ah, I see. I still think the docs/examples could use an update to clarify this. I think our code may have been putting the deadline _into_ a `Metadata` class, since it wasn't immediately obvious from the examples that is wrong.

**Comment by murgatroid99** [comment] 2024-05-30 18:31
I'm not sure what you mean about putting the deadline into a Metadata class. That's clearly not what the example shows.

For clarification, I think the examples collectively cover the different cases. The hello world example demonstrates making a request without providing either metadata or callOptions. The deadline example demonstrates making a request with callOptions but not metadata. The metadata example demonstrates making a request with metadata but not callOptions. And you seem to have figured out how to send both from other information.

**Comment by jhump** [comment] 2024-05-30 18:36
Looks like the issues arise from using TypeScript. The `.ts.d` file generated has signatures like so:
```
public unary(request: connectrpc_conformance_v1_service_pb.UnaryRequest, callback: (error: grpc.ServiceError | null, response: connectrpc_conformance_v1_service_pb.UnaryResponse) => void): grpc.ClientUnaryCall;

public unary(request: connectrpc_conformance_v1_service_pb.UnaryRequest, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: connectrpc_conformance_v1_service_pb.UnaryResponse) => void): grpc.ClientUnaryCall;

public unary(request: connectrpc_conformance_v1_service_pb.UnaryRequest, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: connectrpc_conformance_v1_service_pb.UnaryResponse) => void): grpc.ClientUnaryCall;
```

None of those signatures accepts a `CallOptions` as the second parameter, but the examples clearly show adding the deadline to the second parameter. I think the TS generator needs to also emit another signature:
```
public unary(request: connectrpc_conformance_v1_service_pb.UnaryRequest, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: connectrpc_conformance_v1_service_pb.UnaryResponse) => void): grpc.ClientUnaryCall;
```

**Comment by murgatroid99** [comment] 2024-05-30 20:01
Which code generator is producing those TypeScript files?

**Comment by smaye81** [comment] 2024-05-30 20:38
Actually in looking at how we are generating the `d.ts` files, it is using `grpc_tools_node_protoc_ts`, which isn't a part of grpc-js. I assumed that the `grpc_tools` prefix meant it was part of the [grpc-tools](https://www.npmjs.com/package/grpc-tools) package. We will follow up with that plugin author and we can close this issue.

**Closed** 2024-06-24 23:10 UTC
