### ISSUE TITLE
Error: keys that don't end with '-bin' must have String values (for numeric values)

### ISSUE THREAD

**Issue by breznik** [grpc/grpc-node#364] opened 2018-05-23 17:27 UTC
### Problem description
I am trying to attach a unique request id to the metadata of each outgoing gRPC call from nodejs to a gRPC server. Most of the time this works fine, but occasionally I am getting the error that the node code thinks the value for the key is not a string.

The key name ends in "request_id" - so, definitely not a '-bin' keyname. The value is populated with javascript code:
`Math.floor(Number.MAX_SAFE_INTEGER * Math.random()) + ''`

The error rate is probably < 1% of all calls, but it does happen often enough with volume to be disruptive.

### Environment
- Alpine Linux v3.7
- Node v8.9.3r1
- gRPC@1.6.6

### Additional context
Is there some other way I should be generating a unique request id to attach with the request for debugging/logging purposes? I also tried UUIDv4 and ran into the same issue.

**Comment by nicolasnoble** [comment] 2018-05-23 18:00
When you say you ran into the same issue with uuidv4, do you mean that you would randomly have the same error ?

If that's a yes, my hunch would be that you're didn't diagnose the problem properly, and that the problem comes from another metadata value that's stored in there.

@murgatroid99 it would probably be beneficial to alter the errors in metadata.js to include at least the key name that failed.

**Comment by breznik** [comment] 2018-05-23 18:07
Yes - would randomly have the issue when using uuidv4.

The actual value of the metadata key gets validated on [`set()`](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js-core/src/metadata.ts#L76), so I was able to pinpoint it exactly to this one particular metadata value.

**Comment by breznik** [comment] 2018-05-23 18:08
Also, it might be more valuable to include the key-value that failed.

**Comment by murgatroid99** [comment] 2018-05-23 18:08
What is the exact error you are seeing?

**Comment by breznik** [comment] 2018-05-23 18:08
Error: keys that don't end with '-bin' must have String values

**Comment by nicolasnoble** [comment] 2018-05-23 18:19
Here's the odd thing. This is validated through lodash's `isString`, and that's that. While I could imagine something weird going on with the random number generator, a uuid really should just be a string.

The only other thing I can see is that you're on a fairly old version of gRPC, and we've updated our lodash dependency since then. Might be worth trying to upgrade ?

**Comment by nicolasnoble** [comment] 2018-05-23 19:23
Well, if you can really capture the errors, maybe you could also display the specific key / value that caused the error ? This way we could try reproducing with hardcoding these values.

**Comment by nicolasnoble** [comment] 2018-06-26 21:54
No updates in more than a month, closing.

**Closed by nicolasnoble** 2018-06-26 21:54 UTC
Labels: requires reporter action
