### ISSUE TITLE
Module 'http2' not found

### ISSUE THREAD

**Issue by rakhi2104** [grpc/grpc-node#610] opened 2018-11-02 13:30 UTC
### Problem description
gRPC couldn't initialize due to the missing 'http2' module.

### Reproduction steps
- Use of package `firebase-admin` in React App, bootstrapped with `create-react-app`
- Follow steps from Google Firebase Admin Documentation
- Start the React App using `yarn start` or `npm start`

### Environment
 - Linux Ubuntu 18.04 amd64
 - Node version 10.11.0
 - npm

### Error message 
```bash
Failed Compiling
./node_modules/@grpc/grpc-js/build/src/channel.js
Module not found: Can't resolve 'http2' in '/home/.../project1/node_modules/@grpc/grpc-js/build/src'
```

**Comment by nicolasnoble** [comment] 2018-11-02 14:46
How did you install the Node runtime?

**Comment by rakhi2104** [comment] 2018-11-02 15:02
Followed the standard installation guide [here](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)

**Comment by cjihrig** [comment] 2018-11-02 15:12
What does `node -p process.version` and `node -p http2` display? The `http2` module is built into Node core, so if you're actually using version `10.11.0`, then it should be there.

**Comment by rakhi2104** [comment] 2018-11-02 15:53
`node -p process.version`: outputs `v10.11.0`
`node -p http2`: outputs a list of constants.

**Comment by nicolasnoble** [comment] 2018-11-02 17:17
So, we'd need a more complete reproduction case. The `http2` module seems to be working properly for you, so it failing like this doesn't make a lot of sense.

**Comment by kjin** [comment] 2018-11-02 17:18
`create-react-app` seems to hardcode a list of Node built-in modules that it creates empty mocks: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L451-L457

My guess is that they haven't added `http2` to the list yet.

**Comment by kjin** [comment] 2018-11-02 17:20
`create-react-app` seems to hardcode a list of Node core modules to mock out in the browser: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L451-L457

The problem seems to stem from that it seems like they haven't added `http2` yet.

**Comment by murgatroid99** [comment] 2018-11-02 18:38
If you're using gRPC in a context where you need an empty http2 mock to load it, gRPC won't work because it fundamentally needs http2 to function.

**Comment by nicolasnoble** [comment] 2018-11-02 20:15
I'd also add that you can't make grpc work from the browser in any case. In other words, grpc can't be webpack-ed, therefore, you can't use it in a "react application" out of the box like this.

**Comment by murgatroid99** [comment] 2018-11-02 21:16
If `firebase-admin` is not a necessary dependency of the app, then the correct solution is to omit it from the app, not to force it compile when you know that it won't function.

**Comment by kjin** [comment] 2018-11-02 21:52
It seems like the module isn't supported on the client side: https://www.npmjs.com/package/firebase-admin#supported-environments

**Comment by christopher-johnson** [comment] 2018-11-13 11:53
this issue is related to any library that depends on [google-gax](https://www.npmjs.com/package/google-gax), so it is not specific to firebase-admin.  For example, I am trying to use `@google-cloud/vision`. As noted, mocking `http2` in webpack does not work.  `@google-cloud/vision` is a client-side API, so it should work in the browser, no?

**Comment by christopher-johnson** [comment] 2018-11-13 13:21
I guess that one way forward for browser support for `google-gax` is [grpc-web](https://github.com/grpc/grpc-web)?

**Comment by matiaslato** [comment] 2018-11-26 12:41
:(

**Comment by Muhammad-Wasi** [comment] 2019-04-05 08:10
IiroNiemi Thanks

**Comment by philval** [comment] 2019-09-03 13:14
This happened after I installed the firebase deployment tools today ( ? odd ).  resolved by :

i) **npm install http2**
ii) **npm uninstall firebase-admin** ( personally can see how this is related, but was referred to in some stackoverflow answers )

**Comment by dmitry-yudakov** [comment] 2019-09-27 19:19
In my case the reason for "Module 'http2' not found" error was too old version of node - 8.4.x - set in package.json and used by heroku. It seems it was added by default in 8.8.0. Updating node version to 12.x.x and npm to 6.x.x solved the problem.

**Comment by iboxgithub** [comment] 2019-11-18 23:51
I think @philval is correct the problem comes from firebase-admin. Looks very similar to that
https://github.com/googleapis/nodejs-dialogflow/issues/314
Anyone found a way to use create-react-app with firebase-admin? To reproduce do: 
`npm install firebase admin`
then in your code
`var admin = require("firebase-admin");`

**Comment by FeaturedSpace** [comment] 2020-03-30 16:08
Has this issue been resolved?

**Comment by murgatroid99** [comment] 2020-03-30 16:31
This "issue" is just that there are some environments where the `@grpc/grpc-js` library is not supported. The library is only intended to function on Node versions specified in the `engines` field in the package.json file.

**Closed** 2020-03-30 16:58 UTC
Labels: requires reporter action
