### ISSUE TITLE
Document client options

### ISSUE THREAD

**Issue by anjmao** [grpc/grpc-node#402] opened 2018-06-19 13:22 UTC
### Is your feature request related to a problem? Please describe.
There is no grpc client options documentation.  Client constructor options in Typescript declaration are not described https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.d.ts#L978. I was searching for client options around internet and found them only in C++ header file https://github.com/grpc/grpc/blob/56e59ef6b03c73ecddf0954ee409a3f60ed5ea30/include/grpc/impl/codegen/grpc_types.h#L142.

### Describe the solution you'd like
I would like add client options to index.d.ts file.

### Additional context
I can make a PR for this.

**Comment by murgatroid99** [comment] 2018-06-19 20:37
I agree that this would be useful, but I want to be cautious about essentially maintaining a duplicate of a list with contents that are determined elsewhere.

One of the primary reasons I haven't done this already is because I think it would take a significant amount of work to verify that we have the whole list. Unfortunately, the header file you linked to doesn't have all of the options. For example, there are a few defined in [compression_types.h](https://github.com/grpc/grpc/blob/56e59ef6b03c73ecddf0954ee409a3f60ed5ea30/include/grpc/impl/codegen/compression_types.h). I think there might be others, but I'm not really sure where they are defined. I think it's even possible that there are options that are checked in internal code, but not specified in headers.

One option, of course, would be to just add the known options with a comment mentioning that there might be others, and put a `[key: string]: number | string` at the end of the type. Strictly speaking, that is needed anyway because that's what the intermediate code accepts, and it is part of the API that unknown keys are accepted and ignored.

**Comment by anjmao** [comment] 2018-06-20 06:50
@murgatroid99 Thanks for response. You are right, there are a lot of options. At least other users now will know there to search for options list [grpc_types.h](https://github.com/grpc/grpc/blob/56e59ef6b03c73ecddf0954ee409a3f60ed5ea30/include/grpc/impl/codegen/grpc_types.h#L142.), [compression_types.h](https://github.com/grpc/grpc/blob/56e59ef6b03c73ecddf0954ee409a3f60ed5ea30/include/grpc/impl/codegen/compression_types.h) and maybe some other internal random places 😄

**Comment by bcronje** [comment] 2018-08-06 21:38
Why did you close this issue? It think this is a perfectly valid and still unresolved issue. Just spend some time to actually find anything that will give info on what options are available, if it wasn't for this issue I'd still be looking. Surely at least the known or popular options should be documented in the API?

**Comment by murgatroid99** [comment] 2022-01-18 22:49
The `grpc` package is now deprecated, so this is unlikely to change. The `@grpc/grpc-js` package which replaces it has the supported channel options documented in both the TypeScript types and in its README.

**Closed by murgatroid99** 2022-01-18 22:49 UTC
Labels: package: grpc
