### ISSUE TITLE
Google vision api grpc error for linux environment

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc-node#564] opened 2018-09-29 14:36 UTC
_From @FintechITSolutions on September 29, 2018 6:39_

npm install --save @google-cloud/vision runs for windows properly but it does not install node-gyp for linux, It gives error :
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v57-linux-x64-glib
Found: [node-v57-win32-x64-unknown]

_Copied from original issue: googleapis/nodejs-vision#211_

**Comment by nicolasnoble** [comment] 2018-09-29 14:55
This error means you've been copying your work directory straight from a windows machine to a Linux machine. You need to run `npm rebuild` when you attempt something like this.

**Comment by nicolasnoble** [comment] 2018-09-29 21:44
I'll close this one preemptively, as the problem and resolution are straightforward. You can't simply copy your work directory from one platform to another and hope it'll work, you always need to run `npm rebuild` on the destination machine to get this manipulation to work fine.

**Closed by nicolasnoble** 2018-09-29 21:44 UTC

**Comment by FintechITSolutions** [comment] 2018-10-03 08:05
Sir i have tried npm rebuild but it does not work.

**Comment by nicolasnoble** [comment] 2018-10-03 12:42
You'll need to give us some better reproduction steps then. As specified in our issue template, and issue that doesn't have proper information on how to reproduce the problem ourselves will be closed.

**Comment by nicolasnoble** [comment] 2018-10-03 20:04
You need to use `npm rebuild` *on your domain*. If you simply copy files from your Windows machine to your hosting environment to deploy your nodejs app, you're doing it wrong. I don't know what deployment procedure you're following, but here's an [example of a deployment procedure](https://www.phusionpassenger.com/library/walkthroughs/deploy/nodejs/ownserver/nginx/oss/bionic/deploy_app.html) using phusion passenger, and there's an `npm install --production` step right in the end of it, onto the hosting provider. This is how you deploy a nodejs app in production. Not by copying all of your local directory, but by pushing the code to the hosting provider and running `npm install --production`.

Now, to talk a bit more about your issue, by default, `npm rebuild` will re-install the modules for your local system in case you've changed something such as your version of nodejs. As I said in my first comment, you are copying straight from your Windows machine onto a Linux machine. This isn't going to work, for any dependency that has native modules, not just gRPC. You *need* to be able to run `npm rebuild` on your hosting provider when you have native modules to do it the safest possible way. If you keep running `npm rebuild` on your Windows machine, then copying the result on a Linux host, this won't solve the issue you're having. You need to be able to deploy on your hosting providing by running the command `npm install` on the hosting machine, or `npm rebuild` in worst-case scenario.

Now, with gRPC, since we rely on `node-pre-gyp`, if you really can't run any command on your hosting provider (which is rare, but, well...), you can pre-install the proper binary on your Windows machine, granted you know exactly the target machine's architecture and environment. In your case, you should be able to do:

```
npm rebuild --target=8.12.0 --target_arch=x64 --target_platform=linux --target_libc=glibc
```

I'll have to insist that this is absolutely not the right way to deploy a nodejs app. This above would happen to work in this specific case, but if there's any other native module dependency in your app than grpc, this will probably create more problems than it'll solve them.
