### ISSUE TITLE
Can't build grpc

### ISSUE THREAD

**Issue by zvischutz** [grpc/grpc-node#1067] opened 2019-10-07 08:24 UTC
Can't build grpc - See below log . Version 1.23.4 works fine.
This was the case also with 1.22.0 on 22/August , I just can't find the old issue , not sure why

#gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/opt/nodejs/bin/node /opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v48' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
node-pre-gyp ERR! command "/opt/nodejs/bin/node" "/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc
node-pre-gyp ERR! node -v v6.17.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
npm ERR! Linux 3.10.0-957.1.3.el7.x86_64
npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "i"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.24.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.0 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/npm-debug.log
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.24.0 and node@6.17.1 (node-v48 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error self signed certificate in certificate chain
In file included from ../deps/grpc/third_party/upb/upb/msg.h:14:0,
                 from ../deps/grpc/third_party/upb/upb/generated_util.h:10,
                 from ../deps/grpc/src/core/ext/upb-generated/src/proto/grpc/gcp/transport_security_common.upb.h:12,
                 from ../deps/grpc/src/core/tsi/alts/handshaker/transport_security_common_api.h:29,
                 from ../deps/grpc/src/core/lib/security/credentials/alts/grpc_alts_credentials_options.h:26,
                 from ../deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.h:26,
                 from ../deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.cc:21:
../deps/grpc/third_party/upb/upb/upb.h:27:28: fatal error: upb/port_def.inc: No such file or directory
#include "upb/port_def.inc"
                            ^
compilation terminated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v48"
gyp ERR! cwd /var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/opt/nodejs/bin/node /opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v48' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
node-pre-gyp ERR! command "/opt/nodejs/bin/node" "/var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/node_modules/grpc
node-pre-gyp ERR! node -v v6.17.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
npm ERR! Linux 3.10.0-957.1.3.el7.x86_64
npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "up"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.24.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.0 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/atlassian/application-data/bamboo/xml-data/build-dir/23592965/VAM-VNS-VNSBJ1/npm-debug.log everything. Please try and set your operating system's locale to English, so that logs contain error messages in the English language.

**Comment by yannliao** [comment] 2019-10-07 10:32
same problem,   you can try  this issue : #1057

**Comment by dzhamshed** [comment] 2019-10-21 07:09
Same problem. I downloaded the sources package and found out that it's actually missing two files **port_def.inc** and  **port_undef.inc** in the **grpc/deps/grpc/third_party/upb/upb**. So, I downloaded them manually and when **npm install grpc** downloaded grpc folder I placed them in the corresponding folder, then it started compiling from source. Everything went smooth, but it gave another error that **#include<address_sorting/address_sorting.h> No such file ...**. So, I looked inside the source files of npm grpc package, and it seems missing a lot of dependency files.

Now, I cannot install latest firebase, because it depends on grpc@1.24.0.

Can anybody help with this?

**Comment by murgatroid99** [comment] 2019-10-22 17:22
I have published grpc 1.24.1 with the fix for this.

**Closed by murgatroid99** 2019-10-22 17:22 UTC

**Comment by willks** [comment] 2020-01-01 14:26
I found the cause for my Web UI project tonight. Took me a bit. 

Let me say I'm dumping Firebase forever.

**Comment by gnesher** [comment] 2020-02-04 09:16
> It's just the browser I was using!

what do you mean?

**Comment by MrEmanuel** [comment] 2020-02-27 13:04
I found that the problem was that the package "request" was missing. 
Installing it before installing grpc fixed my issues. 
If you have a package depending on `grpc`, install `request` first.

`yarn add request` 
`yarn add grpc`

A colleague mentioned that some the package "spike" is used if request is not available and that doesn't play nice with the company proxy. Dunno if that's actually the problem, but adding `request`  did fix the issue.
