### ISSUE TITLE
@grpc/proto-loader: Imported protos present in different directory, cannot use keyword new

### ISSUE THREAD

**Issue by YajneshRai** [grpc/grpc-node#470] opened 2018-08-01 16:25 UTC
### Problem description
grpc proto loader does not function same as `grpc.load()` when the imported files exist in different directories, and throws error for using keyword `new`

### Reproduction steps
I have a proto file in the path : `/dir1/dir2/abc.proto` which has imports in it like this:

```
syntax = "proto3";
import "file1.proto"
import "file2.proto"

//proto body 

service ab { 
//rpc methods
}
```

The imported files `file1.proto` and `file2.proto` present in different directoriy `/dir1/imported_files`

I'm trying to load grpc service using `@grpc/proto-loader` like this:

```
grpc = require('grpc');
grpcLoader = require('@grpc/proto-loader');

const options = {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true,
    includeDirs: [ '/dir1/imported_files' ] // tried adding /dir1/dir2 as well
}

const packageDefinition = grpcLoader.loadSync( '/dir1/dir2/abc.proto', options );
const defn= grpc.loadPackageDefinition(packageDefinition);

console.log(packageDefinition, defn, defn.ab); //prints {} {} undefined

def_client= new defn.ab('localhost:50050', grpc.credentials.createInsecure()); // throws error 
```
Error:
```
def_client = new defn.ab('localhost:50050', grpc.credentials.createInsecure());
             ^
TypeError: defn.ab is not a constructor
```

### Environment
 - OS: Ubuntu 16.04.3 LTS
 - Node version: 9.5.0
 - grpc: 1.11.3
 - @grpc/proto-loader: 0.3.0

Sample code with proto files attached

[import_test.zip](https://github.com/grpc/grpc-node/files/2252711/import_test.zip)

**Comment by nicolasnoble** [comment] 2018-08-01 16:43
Without a complete reproduction case, this will be difficult to troubleshoot. If you can't share your actual .proto files, could you try mocking out what's going on so we could reproduce ?

My guess is that there's something invalid in your .proto files, that was being loaded before in protobufjs 5, but is now failing in protobufjs 6.

Also, that'd mean this is not a bug, but rather an issue with your proto files. Try compiling your proto files using protoc, you might get better error messages.

**Comment by YajneshRai** [comment] 2018-08-01 18:10
Since I had imported files in different directories I tried using proto-loader (to get similar functionality as grpc.load() like it is mentioned in the docs), but had no luck with it. I'll soon attach a mock file set to reproduce the issue.

**Comment by YajneshRai** [comment] 2018-08-02 08:28
@nicolasnoble I have attached a zip file with sample code and mock proto data

**Comment by nicolasnoble** [comment] 2018-08-02 19:07
If you're specifying import paths, please do not use absolute paths for the loadings, only relative paths to the import paths you've specified. Your example is fixed by changing this line

```
const PROTO_PATH = __dirname + '/proto/main/person.proto'; 
```

to this line:

```
const PROTO_PATH = 'person.proto';
```

**Closed by nicolasnoble** 2018-08-02 19:07 UTC
Labels: requires reporter action

**Comment by nicolasnoble** [comment] 2018-08-02 19:16
Sorry, and this line:
```
    includeDirs: [ IMPORT_PATH ]
```

to this line:
```
    includeDirs: [ IMPORT_PATH, PROTO_DIR ]
```
