### ISSUE TITLE
Received RST_STREAM with code 2 triggered by internal client error: Session closed with error code 2

### ISSUE THREAD

**Issue by bbit8** [grpc/grpc-node#2672] opened 2024-02-21 12:51 UTC
version: v1.9.14

What is the reason of this error?

2024-02-21 20:35:59.825 [debug] - 2024-02-21T12:35:59.825Z | v1.9.14 72398 | transport | (6) 127.0.0.1:10100 connection closed by GOAWAY with code 2 and data undefined
2024-02-21 20:35:59.825 [debug] - 2024-02-21T12:35:59.825Z | v1.9.14 72398 | subchannel | (5) 127.0.0.1:10100 READY -> IDLE
2024-02-21 20:35:59.826 [debug] - 2024-02-21T12:35:59.826Z | v1.9.14 72398 | subchannel_refcount | (5) 127.0.0.1:10100 refcount 2 -> 1
2024-02-21 20:35:59.826 [debug] - 2024-02-21T12:35:59.826Z | v1.9.14 72398 | pick_first | READY -> IDLE
2024-02-21 20:35:59.826 [debug] - 2024-02-21T12:35:59.826Z | v1.9.14 72398 | resolving_load_balancer | dns:127.0.0.1:10100 READY -> IDLE
2024-02-21 20:35:59.826 [debug] - 2024-02-21T12:35:59.826Z | v1.9.14 72398 | connectivity_state | (4) dns:127.0.0.1:10100 READY -> IDLE
2024-02-21 20:35:59.827 [debug] - 2024-02-21T12:35:59.827Z | v1.9.14 72398 | resolving_load_balancer | dns:127.0.0.1:10100 IDLE -> CONNECTING
2024-02-21 20:35:59.827 [debug] - 2024-02-21T12:35:59.827Z | v1.9.14 72398 | connectivity_state | (4) dns:127.0.0.1:10100 IDLE -> CONNECTING

2024-02-21 20:35:59.832 [debug] - 2024-02-21T12:35:59.832Z | v1.9.14 72398 | subchannel_call | [7107] Node error event: message=Session closed with error code 2 code=ERR_HTTP2_SESSION_ERROR errno=Unknown system error undefined syscall=undefined
2024-02-21 20:35:59.832 [debug] - 2024-02-21T12:35:59.832Z | v1.9.14 72398 | subchannel_call | [6870] HTTP/2 stream closed with code 2
2024-02-21 20:35:59.832 [debug] - 2024-02-21T12:35:59.832Z | v1.9.14 72398 | subchannel_call | [6870] ended with status: code=13 details="Received RST_STREAM with code 2 triggered by internal client error: Session closed with error code 2"

**Comment by murgatroid99** [comment] 2024-02-21 18:35
This is a duplicate of #2647. The answer you are looking for is probably already there, and if not, please continue the conversation in that issue.

**Closed by murgatroid99** 2024-02-21 18:35 UTC
