### ISSUE TITLE
Typings issue in version 1.13.0

### ISSUE THREAD

**Issue by gunblues** [grpc/grpc-node#425] opened 2018-07-09 08:34 UTC
If I run tsc -d on my Typescript source I get the following message:

```
node_modules/grpc/index.d.ts:69:50 - error TS2314: Generic type 'Message<T>' requires 1 type argument(s).

69     [name: string]: GrpcObject | typeof Client | Message;
                                                    ~~~~~~~
```

grpc-node version: 1.13.0
Typescript version: 2.9.2
tsconfig.json compiler options:

```
"compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true
  }
```

I have found this issue had been fixed before - https://github.com/grpc/grpc-node/issues/176
it had been restored back after this commit - https://github.com/grpc/grpc-node/commit/abb05f0c1277ed6fe21ceda4674a4c8d41e64d38#diff-84a425dc635cd3214797bf694fad81e8

**Comment by nicolasnoble** [comment] 2018-07-09 11:36
There seems to be a tug-of-war on this one, and a more thorough discussion is needed. See the following pull requests:

https://github.com/grpc/grpc-node/pull/393
https://github.com/grpc/grpc-node/pull/422

**Comment by murgatroid99** [comment] 2018-07-09 22:05
@gunblues Would you mind sharing the output of `npm ls` in your project directory?

**Comment by nicolasnoble** [comment] 2018-07-10 12:16
What's the story exactly when one uses `@grpc/proto-loader` which uses protobufjs 6 ?

**Comment by andrew8er** [comment] 2018-07-10 14:47
As far as I see it, grpc-node is both compatible with protobufjs 5 and 6 (I use it with version 6). So neither version of message is _right_. This whole adding and removing of the generic parameter does not fix the problem:

grpc-node should not make _any_ assumptions on the encoding format and thus should not depend directly on protobufjs, regardless of version.

**Comment by nicolasnoble** [comment] 2018-07-10 15:20
Yes, you're correct - what's your suggestion to do this properly ?

**Comment by andrew8er** [comment] 2018-07-11 08:16
On a high level, there should be an adapter object that is passed to the service description loading mechanism and that takes care of converting from raw buffers to Js objects and vice versa. This adapter would need to live in its own package and depend on its respective wire format library, so users will only drag in the dependencies necessary for their use case.

So we would have packages `grpc-codec-protobufjs5`, `grpc-codec-protobufjs6`, maybe even `grpc-codec-thrift`, `grpc-codec-capnproto`.

Currently, `grpc-node` does some guesswork to determine if it is run with `protobufjs` version 5 or 6 (please correct me, if I'm wrong). This should be done explicitly via an API as mentioned above.

Furthermore, we would need to get rid of any direct dependency on `protobufjs` in the whole `grpc-node` package (and consequently in its type definition file). Only the codec adapter would have that dependency.

Actually, I think we are not too far away from that. The `Message` occurs only once in the definition file. `grpc-node` already has `serialize<T>` and `deserialize<T>` type.

Btw. has anybody seen a project that uses gRPC with something other than protobuf?

**Comment by murgatroid99** [comment] 2018-07-11 15:56
Is this suggestion substantially different from the `@grpc/proto-loader` library and the `addPackageDefinition` API that was recently added to the grpc library?

As for removing the `protobufjs` dependency from grpc, the main problem there is that for various reasons we can't make breaking changes. So we have to work with what we have.

**Comment by murgatroid99** [comment] 2018-07-12 15:55
The proto loader library specifically uses Protobuf.js 6. Protobuf.js 5 is outdated, and the `grpc` library only still uses it for API compatibility reasons. But the `loadPackageDefinition` function is generic, and can work with any kind of serialization. That API is public, so anyone can write one of the other serialization libraries you suggest.

As I said, we can't make breaking changes, so I wouldn't expect `load`, `loadObject`, and `GrpcObject` to go away in the near future. However, those functions are not implemented in the `@grpc/grpc-js` library, so people who switch to that will not have to worry about that.

**Comment by andrew8er** [comment] 2018-07-16 10:21
The problem is that `grpc-node` depends on `protobufjs-5`. It references the `Message` type from that package in its definition file, so you can only use it with that version without getting a compiler error.

If you are writing a gRPC _server_, the `@grpc/grpc-js` package will not help you, since as far as I know, it does not support the server side API. The `@grpc/proto-loader` package alone will not help you either, since you also will pull in the `grpc-node` definitions somewhere. That definition file is part of the package's public API for Typescript users, so for them, this was already a breaking change. 

A possible solution is to remove the reference to `protobufjs` in the definition file and instead use a local definition of `Message` which is compatible with both versions.

Another stop gap solution everyone affected by this issue is to use a customized definition file. You need to configure your Typescript compiler to pick up this version for the `grpc` module:

```javascript
{
  "compilerOptions": {
    "baseUrl": ".", // This must be specified if "paths" is.
    "paths": {
      "grpc": ["custom/grpc/defintition/file"] // This mapping is relative to "baseUrl"
    }
  }
}
```

**Comment by nicolasnoble** [comment] 2018-07-16 14:44
I think I like the custom Message definition idea, but what exactly would it be like? I can't really think of anything else than something very generic like "object".

**Comment by andrew8er** [comment] 2018-07-16 20:22
True, the API of `Message`differs significantly for both versions (comparing [protobuf5](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ea0b9196a6a66463de5ad3f6562195431d1a1780/protobufjs/protobufjs.d.ts) and [protobuf6](https://github.com/dcodeIO/protobuf.js/blob/462132f222d8febb8211d839635aad5b82dc6315/index.d.ts)). So I would declare an empty _facade_ type and users would be required to cast to their appropriate implementation type.

Typescript has no _opaque_ type, but the new [`unknown`](https://github.com/Microsoft/TypeScript/pull/24439) type might be of help.

**Comment by kjin** [comment] 2018-07-16 22:49
Apologies for not looking into the Protobuf 5-6 tussle more when I introduced the change back to non-generic `Message`.

Would it be worthwhile to open a PR to change pb6 types to have a default `Message<T extends object = object>` type parameter?

**Comment by nicolasnoble** [comment] 2018-07-16 23:34
That might be a good quick fix, yes.

**Comment by murgatroid99** [comment] 2018-07-19 00:19
That PR has been merged and published, so this should no longer be a problem if you update

**Comment by nicolasnoble** [comment] 2018-07-19 01:16
And now it has :-D

**Closed by nicolasnoble** 2018-07-19 01:16 UTC
