### ISSUE TITLE
@grpc/grpc-js & grpc.max_metadata_size

### ISSUE THREAD

**Issue by hugebdu** [grpc/grpc-node#1533] opened 2020-08-12 12:51 UTC
### Is your feature request related to a problem? Please describe.
In order to migrate from `grpc` to `grpc-js` as [suggested](https://github.com/grpc/grpc-node/issues/1531#issuecomment-671611729) I need to be able to specify [`gprc.max_metadata_size`](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L286), which [isn't supported](https://github.com/grpc/grpc-node/blob/master/PACKAGE-COMPARISON.md) currently. 

If I understand correctly, the default of 64k [is implied by the core `http2` module](https://nodejs.org/api/http2.html#http2_settings_object) and supporting it seems to be [pretty easy](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/server.ts#L249-L254)

**Comment by murgatroid99** [comment] 2020-08-12 22:01
Unfortunately, it's not that simple. According to my team, that setting you linked is just advisory. The other libraries need to do explicit enforcement of that option and I can't find anything in the Node `http2` docs about restricting the size of received header blocks, so implementing this may require a change to Node itself.

**Comment by hugebdu** [comment] 2020-08-13 06:11
well in our case we need to increase it actually.
I tried sending trailers with metadata size of > 32K using `@grpc/grpc-js` and the response never gets back to the client.

**Comment by murgatroid99** [comment] 2020-08-13 17:48
That sounds like a bug. A stream hanging like that is never an intended outcome, even if there is a violation of that kind of restriction.

**Comment by hugebdu** [comment] 2020-08-16 07:07
@murgatroid99 so on my machine the threshold is ~64K, not 32K - my bad. 
[test to reproduce](https://github.com/hugebdu/grpc-js-metadata/blob/master/test/server.spec.ts)

**Comment by murgatroid99** [comment] 2020-08-24 18:10
That is interesting. I don't know what might cause that. One potentially important thing to note there is that that parameter that you are using is for sending trailing metadata. You can send headers using the `call.sendMetadata` method.

**Comment by hugebdu** [comment] 2020-08-25 07:07
Yup, tried that as well. Same result

**Comment by murgatroid99** [comment] 2020-08-25 16:42
OK, I tried changing the value of the setting that you linked to on both the client and the server, and that did not change the behavior of the test. So that's definitely not the right solution here.

I think the next step is to create the same test using only Node's built in http2 module. If that has the same behavior, then this is definitely a bug in Node itself, and an issue should be filed there.

**Comment by hugebdu** [comment] 2020-08-26 16:46
I played with that setting as well.
will try to find some time and check the http2 layer apart. will update.
10x

**Comment by hugebdu** [comment] 2020-09-03 08:28
Michael, hey.

Spent some time investigating further and got some findings.
[Here](https://github.com/hugebdu/grpc-js-metadata/blob/master/test/http2.spec.ts#L6) you can find the raw `http2` only reproduction. And apparently [adding `maxSendHeaderBlockLength `](https://github.com/hugebdu/grpc-js-metadata/blob/master/test/http2.spec.ts#L8) to `ServerOptions` solves the problem. Also verified [with the original test](https://github.com/hugebdu/grpc-js-metadata/blob/master/test/server.spec.ts#L44).

Do you think you can now support `gprc.max_metadata_size` propertly?

Thanks

**Comment by murgatroid99** [comment] 2020-09-03 18:19
Now that you have a reproduction using only the `http2` library, it is clearly a Node bug, so you should file an issue against Node itself. In the meantime, I can set that option internally to a large number to work around the bug.

As I mentioned in my previous comment, the `grpc.max_metadata_size` option is for enforcing the upper limit, so it's not relevant to fixing this.

The documentation for `maxSendHeaderBlockLength` says

> Attempts to send headers that exceed this limit will result in a `'frameError'` event being emitted and the stream being closed and destroyed.

If you set that option and then exceed it, do you get the `'frameError'` event or does it still just hang?

**Comment by hugebdu** [comment] 2020-09-06 05:34
Michael, I don't think there's an issue with node's `http2`.

The server indeed [emits `frameError`](https://github.com/hugebdu/grpc-js-metadata/blob/master/test/http2.spec.ts#L19) event, which contains [the stream id among other info](https://nodejs.org/api/http2.html#http2_event_frameerror).

As for the client side - client only [gets the `close` event](https://github.com/hugebdu/grpc-js-metadata/blob/master/test/http2.spec.ts#L52).

Probably `@grpc-js` should listen to the session's `frameError` event (somewhere [here](https://github.com/grpc/grpc-node/blob/7efc5358e3bb56acbea937fef246524f626da0e5/packages/grpc-js/src/server.ts#L615-L626)?) and send back to the client some appropriate [status code](https://developers.google.com/maps-booking/reference/grpc-api/status_codes) - (`DATA_LOSS`, `INTERNAL`, `OUT_OF_RANGE` - you name it)

**Comment by hugebdu** [comment] 2020-09-06 05:48
**UPD**
well, since it happens in this scenario upon trailers frame, looks like it is too late to send appropriate status code

```
Error [ERR_HTTP2_HEADERS_SENT]: Response has already been initiated.
    at ServerHttp2Stream.respond (internal/http2/core.js:2504:13)
```

Then maybe just adding a log/error message?
IMO still better than ignoring `frameError` completely.

WDYT?

**Comment by murgatroid99** [comment] 2020-09-06 21:47
Wait, the client gets the `close` event? That changes everything. The grpc-js client [handles the `close` event](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call-stream.ts#L514), and it should be ending the call when that happens.

**Comment by hugebdu** [comment] 2020-09-07 07:39
The client does get `close` event eventually. Might be due to `mocha` test end run - need to verify that.
However the original (grpc client) still halts, so something isn't right anyway.

**Comment by hugebdu** [comment] 2020-09-07 08:55
Michael, added debug printouts into [call-stream.ts#attachHttp2Stream](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call-stream.ts#L444-L575) events and I don't get the `close` event [in my halting test](https://github.com/hugebdu/grpc-js-metadata/blob/master/test/server.spec.ts#L44)

Also tried adding `frameError` event handler into [server-call.ts#Http2ServerCallStream](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/server-call.ts#L379) constructor that simply destroys the stream

```
        this.stream.on('frameError', () => {
          this.stream.destroy();
        })
```

and now I don't see any halts any more, instead I get an error 
```
Error: 13 INTERNAL: Received RST_STREAM with code 0
    at Object.callErrorFromStatus (node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/src/client.ts:334:36)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/src/client-interceptors.ts:434:34)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/src/client-interceptors.ts:397:48)
```

probably can be improved with some other error code?

**Comment by murgatroid99** [comment] 2020-09-09 19:00
The [`frameError` documentation](https://nodejs.org/api/http2.html#http2_event_frameerror) says

> If the `'frameError'` event is associated with a stream, the stream will be closed and destroyed immediately following the `'frameError'` event. If the event is not associated with a stream, the `Http2Session` will be shut down immediately following the `'frameError'` event.

Closing and destroying the stream should trigger the `'close'` event. If that is not happening, that is a bug in Node.

**Comment by murgatroid99** [comment] 2020-09-09 23:54
After doing my own testing, I have filed nodejs/node#35133. I will also figure out a good setting for `maxSendHeaderBlockLength` to avoid this issue in the future.

**Comment by hugebdu** [comment] 2020-09-10 09:01
@murgatroid99 thanks!

**Closed** 2020-11-05 21:29 UTC
