### ISSUE TITLE
Running Node with --preserve-symlinks

### ISSUE THREAD

**Issue by mleffert** [grpc/grpc-node#735] opened 2019-02-14 14:25 UTC
### Problem description
Running a project with any dependency of gRPC and --preserve-symlinks will not start and throw this error. I was able to remove this and it ran fine.

```
Uncaught Error: Module did not self-register.
  Module._extensions..node	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  import	
  fs.readdirSync.filter.forEach.file	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  module.exports	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.require	
  require	
  (anonymous function)	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.runMain	
  startup	
  (anonymous function)	

```

### Reproduction steps
Start any project with this as a dependency and use the node flag --preserve-symlinks

### Environment
 - Tested on both Mac and Windows 10
 - 8.12.4 and 10.14.1
 - nvm
 - "@grpc/grpc-js": "^0.3.0" 
 - "grpc": "^1.16.0

**Comment by murgatroid99** [comment] 2019-02-14 18:06
I suspect the root cause of your problem is this, from the documentation for that option:

> Note, however, that using `--preserve-symlinks` can have other side effects. Specifically, symbolically linked *native* modules can fail to load if those are linked from more than one location in the dependency tree (Node.js would see those as two separate modules and would attempt to load the module multiple times, causing an exception to be thrown).

The `grpc` library uses a native module, so the situation you describe is likely to happen if you depend on `grpc` at least twice directly or indirectly. The `@grpc/grpc-js` library should not have that problem because it does not use a native module.

**Comment by mleffert** [comment] 2019-02-14 18:42
I set up a work around where I don't need that command and it fixed my issue. Spent the better half of a week trying to figure out what was up till I spun it up on another machine. Thank you for the information. Thought I would drop a line just in case there was something to be done for it.

**Comment by murgatroid99** [comment] 2019-03-04 18:49
I am closing this issue because the Node documentation directly states that you should not use that option with a package with a native module like `grpc`.

**Closed by murgatroid99** 2019-03-04 18:49 UTC
