### ISSUE TITLE
@grpc/grpc-js hangs forever on stub method invocation when server is unavailable

### ISSUE THREAD

**Issue by LINKIWI** [grpc/grpc-node#924] opened 2019-06-23 21:51 UTC
### Problem description

`@grpc/grpc-js` hangs forever on an RPC invocation when the remote server is unavailable. This is inconsistent with the behavior of `grpc` which fails immediately with `Status.UNAVAILABLE`

### Reproduction steps

Given a service definition:

```
service Service {
    rpc Method(...) returns (...);
}
```

With no server listening and no deadline specified, the following hangs forever instead of failing immediately:

```
import * as grpc from '@grpc/grpc-js';
import * as protoLoader from '@grpc/proto-loader';

const def = protoLoader.loadSync(...);
const descriptor = grpc.loadPackageDefinition(def);
const stub = new descriptor.Service(...);
stub.method();
```

The following correctly fails immediately with `Status.UNAVAILABLE`:

```
import grpc from 'grpc';
import * as protoLoader from '@grpc/proto-loader';

const def = protoLoader.loadSync(...);
const descriptor = grpc.loadPackageDefinition(def);
const stub = new descriptor.Service(...);
stub.method();
```

### Environment

Reproducible on all platforms, Node versions, and versions of @grpc/grpc-js

### Additional context

One workaround I've identified from searching online is to always set a deadline for stub method invocations. However, this is unwieldy and nonideal since even the initial connection to the server will take at minimum `deadline - current time` units of time even if the server is not up.

**Comment by murgatroid99** [comment] 2019-06-24 17:28
Yes, this is a bug. Essentially, `grpc-js` behaves as though the `wait_for_ready` option is always set, which means that it keeps trying to connect instead of ending calls with an `UNAVAILABLE` status at the first connection error.

**Comment by LINKIWI** [comment] 2019-06-25 02:31
I see, thanks for the insight. I saw #896 but was not sure if it was the same root issue since I am not familiar with grpc internals. Feel free to deduplicate for easier tracking.

**Comment by murgatroid99** [comment] 2019-06-25 18:07
Yes, this is a duplicate of that issue.

**Closed by murgatroid99** 2019-06-25 18:07 UTC
