### ISSUE TITLE
@grpc/grpc-js : SNI is not Supported

### ISSUE THREAD

**Issue by ctrlshp** [grpc/grpc-node#1462] opened 2020-06-04 19:43 UTC
I am using `@grpc/grpc-js` (1.0.4) as a client. There is no way to set the `servername` parameter anywhere when instanciating a new client via `new Client()`. As a result, a server requiring SNI will return a random certificate which the client will reject if it doesn't match what was in the `address`parameter of the `Client` constructor. Did I miss anything or is there actually no way of doing this properly right now ? Should something like that go in the `ChannelCredentials.createSsl` or something ? Thanks.

**Comment by murgatroid99** [comment] 2020-06-04 20:50
Those TLS options like `servername` are handled internally. My expectation was that the `host` would be used if the `servername` is not set. If that is not true, I can fix that.

If the problem is that the server name is different from the server's DNS address, that can be addressed by using the `'grpc.ssl_target_name_override'` `Client` constructor option, like this:

```ts
new Client(target, grpc.credentials.createSsl(), {'grpc.ssl_target_name_override': servername});
```

**Comment by ctrlshp** [comment] 2020-06-04 22:37
Hi ! No, It doesn't seem to be the case (that the servername is set according to the `http2.connect` `uri` parameter). The `servername` should be set independently of the HTTP `host`header and it doesn't seem to be the case now. I might be wrong, of course. But I set the `servername`on every `tls.connect`. You can take it straight from the parsed URI, though.

**Comment by murgatroid99** [comment] 2020-06-04 22:44
I'm not talking about the `uri` parameter or any headers. I'm talking about the `tls.connect` `host` option.

Can you clarify whether you are describing a connection failure you are experiencing when using `@grpc/grpc-js`, or a problem you found when examining the code?

**Comment by ctrlshp** [comment] 2020-06-05 13:51
I was talking about the `tls.connect` `host` vs `servername`that you are getting from the `Client` constructor. I am no investigating if this could be a misbehaviour of the server instead as setting the `grpc.ssl_target_name_override`to the servername corresponding to the certificate the server is sending back allows the client to connect. I will investigate in the next few days and get back to you then. Thanks.

**Comment by murgatroid99** [comment] 2020-06-05 16:21
I think that that actually confirms that the problem is what you said. `grpc.ssl_target_name_override` sets `servername` internally.

**Closed** 2020-06-15 22:01 UTC

**Comment by murgatroid99** [comment] 2020-06-18 17:21
A change that should fix this is now out in version 1.1.0.

**Comment by mbwhite** [comment] 2020-06-19 15:45
Hi - the 1.1.0 update trigger a failure in our tests when a connection was being established.

```
172.21.0.6:9052 connection closed with error Hostname/IP does not match certificate's altnames: Host: peer0.org2.example.com:9052. is not in the cert's altnames: DNS:peer0.org2.example.com
```
Is the error I get from the extra grpc logging. This change looks to be related - however I'm not certain why, or exactly what the error is implying

The server in this case (peer0) is in another docker container and is a go server.

**Comment by murgatroid99** [comment] 2020-06-19 15:59
@mbwhite A fix for that is incoming in #1486.

**Comment by murgatroid99** [comment] 2020-06-19 18:16
1.1.1 is out with that fix.

**Comment by CMCDragonkai** [comment] 2021-04-20 08:10
Does this option `grpc.ssl_target_name_override` have any effect when used on `grpc.Server`?

Or is the `servername` only applicable on the client side? What happens if my GRPC server only has an IP and does not have a name at all?

**Comment by murgatroid99** [comment] 2021-04-20 17:00
No, that option is used for validating the certificate you get from the server, so I don't know what it would do on the server.

I think it is possible for a certificate's name to be an IP address, so if a server doesn't have a DNS name, I assume that's how you would handle it.

**Comment by jiangtaoli2016** [comment] 2021-04-20 17:56
`grpc.ssl_target_name_override` should only be used on the client side.
