### ISSUE TITLE
`@grpc/grpc-js`: bidi streaming server sending to closed stream after abrupt client hangup

### ISSUE THREAD

**Issue by wcjohnson** [grpc/grpc-node#984] opened 2019-08-05 01:57 UTC
### Problem description
Occasionally, when a client of a bidirectional-streaming gRPC endpoint hangs up abruptly, it appears that `@grpc/grpc-js` will still attempt to send a final response even when the stream is no longer open.

This is causing an app crash:

```
2019-08-05T01:36:26.352Z node-control-plane Envoy peer hung up:  cluster:default:id:default_envoy-ingress-779c4bc4df-pxd4v
2019-08-05T01:36:26.354Z node-control-plane Node will disconnect:  cluster:default:id:default_envoy-ingress-779c4bc4df-pxd4v
2019-08-05T01:36:26.354Z node-control-plane:environment environment ingress : node cluster:default:id:default_envoy-ingress-779c4bc4df-pxd4v left
2019-08-05T01:36:26.354Z node-control-plane:environment:obnoxious environment ingress membership: []
internal/http2/core.js:2333
      throw new ERR_HTTP2_INVALID_STREAM();
      ^

Error [ERR_HTTP2_INVALID_STREAM]: The stream has been destroyed
    at ServerHttp2Stream.respond (internal/http2/core.js:2333:13)
    at Http2ServerCallStream.sendMetadata (/app/node_modules/@grpc/grpc-js/build/src/server-call.js:213:21)
    at Http2ServerCallStream.sendStatus (/app/node_modules/@grpc/grpc-js/build/src/server-call.js:303:18)
    at ServerDuplexStreamImpl._final (/app/node_modules/@grpc/grpc-js/build/src/server-call.js:129:19)
    at callFinal (_stream_writable.js:617:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Reproduction steps
This one is very difficult to reproduce, and I'm having trouble producing a minimal case. The above stack trace was produced by having an Envoy proxy connect via gRPC to a control plane in a GKE cluster and then killing the Envoy pod. The grpc-js control plane then crashes with that stack trace.

I can't cause it with an Envoy on localhost talking to a grpc-js on localhost, so it appears to be sensitive to network timing.

### Environment
 - OS name, version and architecture: GKE/ContainerOS, Kube master @ 1.12.7-gke.25
 - Node version 10.16.0
 - Node installation method: Docker via node:10.16.0 image
 - Package name and version: @grpc/grpc.js 0.5.2

**Comment by cjihrig** [comment] 2019-08-05 02:14
[This](https://github.com/cjihrig/grpc-server-js/blob/b1f0072aa97b62e978716a7f3cc74e6b96871770/lib/server-call.js#L45-L46) is how I solved the problem in another gRPC server implementation.

**Comment by saikoux12** [comment] 2020-02-27 13:22
@cjihrig  how to solve this problem? how to use your code.... Help me ~

**Comment by cjihrig** [comment] 2020-02-27 14:05
@saikoux12 my code is in a different repo - see the link in my previous comment. However, I think the issue is most likely resolved in this repo. Are you trying with recent versions of node and `@grpc/grpc-js`? I'm asking because this issue is almost 7 months old and there have been a lot of bug fixes.

**Comment by saikoux12** [comment] 2020-02-28 01:36
i use nodejs v12 and @grpc/grpc-js 0.6.18
it's a very simple demo.

this is server.js
```
var PROTO_PATH = __dirname + '/../protos/helloworld.proto';

var grpc = require('@grpc/grpc-js');
var protoLoader = require('@grpc/proto-loader');
var packageDefinition = protoLoader.loadSync(
    PROTO_PATH,
    {keepCase: true,
     longs: String,
     enums: String,
     defaults: true,
     oneofs: true
    });
var hello_proto = grpc.loadPackageDefinition(packageDefinition).helloworld;

function sayHello(call, callback) {
  // callback(null, {message: 12345});
}

function main() {
  var server = new grpc.Server();
  server.addService(hello_proto.Greeter.service, {sayHello: sayHello});
  server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure());
  server.start();
}

main();
```

this is client.js
```
var PROTO_PATH = __dirname + '/../protos/helloworld.proto';

var grpc = require('grpc');
var protoLoader = require('@grpc/proto-loader');
var packageDefinition = protoLoader.loadSync(
  PROTO_PATH,
  {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
var hello_proto = grpc.loadPackageDefinition(packageDefinition).helloworld;

function main() {
  var client = new hello_proto.Greeter('localhost:50051',
    grpc.credentials.createInsecure());
  var user;
  if (process.argv.length >= 3) {
    user = process.argv[2];
  } else {
    user = 'world';
  }
  client.sayHello({ name: user }, function (err, response) {
    console.log('Greeting:', response.message);
  });
}

main();
```


i run server.js first, then run client.js, of course it dosen't have response, because the sayHello function is not callback. Now stop the client.js, the server will shutdown and have error.

**Comment by murgatroid99** [comment] 2020-02-28 01:41
That looks like an entirely different problem. You should file a new issue describing that problem. Make sure to include what error message(s) you are seeing.

**Comment by saikoux12** [comment] 2020-02-28 01:53
sure

**Comment by murgatroid99** [comment] 2020-03-31 22:16
I have made some significant changes to the code paths that handle those messages. Has anyone experienced this bug with grpc-js version 0.7.1?

**Comment by wcjohnson** [comment] 2020-07-18 10:56
I have not seen this issue repeat since upgrading to grpc/grpc-js 1.x.x.

**Closed** 2020-11-16 20:28 UTC
Labels: package: @grpc/grpc-js
